export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_IN_PROGRESS = 'AJAX_CALL_IN_PROGRESS';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const LOAD_PATIENT_SUCCESS = 'LOAD_PATIENT_SUCCESS';
export const UPDATE_PATIENT_SUCCESS = 'UPDATE_PATIENT_SUCCESS';
export const LOAD_DOCTOR_SUCCESS = 'LOAD_DOCTOR_SUCCESS';
export const UPDATE_DOCTOR_SUCCESS = 'UPDATE_DOCTOR_SUCCESS';
export const CREATE_PATIENT_SUCCESS = 'CREATE_PATIENT_SUCCESS';
export const LOAD_APPOINTMENT_DOCTOR ='LOAD_APPOINTMENT_DOCTOR';
export const USER_SIGNUP_SUCCESS='USER_SIGNUP_SUCCESS';
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS';
export const USER_LOGOUT_SUCCESS='USER_LOGOUT_SUCCESS';

